Application from Itering for Q4 2024 - Q1 2025
ringecosystem/collaboration pull request #87
Opened 2024-10-25 03:44 UTC by AurevoirXavier

2024-10-25 03:59 UTC, hackfisher requested changes

2024-10-25 03:59 UTC, hackfisher commented on service-providers/itering/24q4-25q1.md
> +- Address: 3 FRASER STREET #04-23A DUO TOWER SINGAPORE (189352)
```suggestion
```

2024-10-25 03:59 UTC, hackfisher requested changes

2024-10-25 03:59 UTC, hackfisher commented on service-providers/itering/24q4-25q1.md
> +costs: x,xxx,xxx RING
```suggestion
costs: x,xxx,xxx USDC
```

2024-10-28 08:42 UTC, boundless-forest approved these changes
LGTM. Let's merge this first and complete the todos in future PRs.

2024-10-30 03:08 UTC, merged